<?php
// Token and chat_id are NOT here. They are in a separate file tg.txt (two lines):
//   line 1 = bot token
//   line 2 = chat_id
// Do NOT edit this file. ASCII-only on purpose.

header('Access-Control-Allow-Origin: *');
header('Content-Type: application/json; charset=utf-8');

// Version-safe HTTP status (works on PHP < 5.4 too, no http_response_code()).
function respond($code, $payload) {
    $texts = array(
        200 => 'OK',
        400 => 'Bad Request',
        405 => 'Method Not Allowed',
        500 => 'Internal Server Error',
    );
    $proto = isset($_SERVER['SERVER_PROTOCOL']) ? $_SERVER['SERVER_PROTOCOL'] : 'HTTP/1.1';
    $text  = isset($texts[$code]) ? $texts[$code] : '';
    header($proto . ' ' . $code . ' ' . $text);
    echo json_encode($payload);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    respond(405, array('error' => 'Method not allowed'));
}

$cfgPath = dirname(__FILE__) . '/tg.txt';
$botToken = '';
$chatId = '';
if (is_readable($cfgPath)) {
    $lines = file($cfgPath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    if (isset($lines[0])) { $botToken = trim($lines[0]); }
    if (isset($lines[1])) { $chatId = trim($lines[1]); }
}

if ($botToken === '' || $chatId === '') {
    respond(500, array('error' => 'Telegram is not configured (tg.txt missing or empty)'));
}

$input = json_decode(file_get_contents('php://input'), true);
if (!is_array($input)) {
    respond(400, array('error' => 'Invalid JSON'));
}

$name    = isset($input['name'])  ? trim($input['name'])  : '-';
$phone   = isset($input['phone']) ? trim($input['phone']) : '-';
$message = (isset($input['message']) && trim($input['message']) !== '') ? trim($input['message']) : '';
$page    = isset($input['page'])  ? trim($input['page'])  : '-';

$text  = "Novaya zayavka s sayta\n\n";
$text .= "Name: " . $name . "\n";
$text .= "Phone: " . $phone . "\n";
if ($message !== '') {
    $text .= "Message: " . $message . "\n";
}
$text .= "Page: " . $page;

$url    = "https://api.telegram.org/bot" . $botToken . "/sendMessage";
$params = array('chat_id' => $chatId, 'text' => $text);

$ok = false;
$details = '';

if (function_exists('curl_init')) {
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($params));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_TIMEOUT, 15);
    $resp = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $details = ($resp === false) ? curl_error($ch) : $resp;
    curl_close($ch);
    $ok = ($code >= 200 && $code < 300);
}

if (!$ok) {
    $context = stream_context_create(array(
        'http' => array(
            'method'        => 'POST',
            'header'        => "Content-Type: application/x-www-form-urlencoded\r\n",
            'content'       => http_build_query($params),
            'timeout'       => 15,
            'ignore_errors' => true,
        ),
        'ssl' => array('verify_peer' => false, 'verify_peer_name' => false),
    ));
    $resp = @file_get_contents($url, false, $context);
    if ($resp !== false) {
        $decoded = json_decode($resp, true);
        $ok = (is_array($decoded) && !empty($decoded['ok']));
        $details = $resp;
    }
}

if ($ok) {
    respond(200, array('status' => 'success'));
} else {
    respond(500, array('error' => 'Telegram request failed', 'details' => $details));
}
?>
